DIRNAME=classic_edge_detectors
VERSION=1.2
TARGET=classic_edge_detectors_$(VERSION).zip
all: $(TARGET)


$(TARGET):
	zip -9r $@ $(DIRNAME) -x $(DIRNAME)/edges $(DIRNAME)/.DS_Store


DEST=./public_html/files/ipol
HOST=purple
#DEST=./webdocs/files/ipol
#HOST=ampere

upload: $(TARGET)
	rsync -avzu $(TARGET) $(HOST):$(DEST)
	ssh $(HOST) 'chmod -R a+rX $(DEST)'

clean:
	-rm -f $(TARGET)

